source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

inhibit_all_warnings!

abstract_target 'Minnie' do

  pod 'YTKNetwork'
  pod 'SDWebImage'
  pod 'SDWebImage/GIF'
  pod 'Masonry'
  pod 'Mantle'
  pod 'TZImagePickerController'
  pod 'AVOSCloudIM'
  pod 'MBProgressHUD'
  pod 'MJRefresh', '3.1.15.3'
  pod 'YYText'
  pod 'StreamingKit'
  pod 'VIMediaCache'
  #pod 'Fabric'
  #pod 'Crashlytics'
  pod 'Bugly'
  pod 'YYCategories'
  pod 'Qiniu'
  #pod 'PinYin4Objc'
target 'MinnieStudent'
target 'MinnieTeacher'

end
